version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app-server
      - app-front
  app-redis:
    # 指定镜像
    container_name: app-redis
    restart: always
    build: 
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
  app-mysql:
    container_name: app-mysql
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    volumes:  
      - ./dockerRunningFile/db/mysql:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
  app-server:
    container_name: app-server
    restart: always
    build: 
      context: ./app-server
    working_dir: /app-server
    volumes:
      - ./app-server:/app-server
      - ./settings-docker.xml:/root/.m2/settings-docker.xml
      - ./dockerRunningFile/maven/.m2/repository:/root/.m2/repository
    expose:
      - "31134"
    ports:
      # 端口映射
      - 31134:80
    links:
      - app-mysql
      - app-redis
    depends_on:
      - app-redis
      - app-mysql
    command: /usr/local/bin/wait-for-it.sh app-mysql:3306 -- mvn clean spring-boot:run --settings /root/.m2/settings-docker.xml 
  app-front:
    container_name: app-front
    working_dir: /app
    ports:
      # 端口映射
      - 31133:80
    build: 
      context: ./app-front
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./app-front/app/dist:/app/dist