version: '3'
services:
  redis:
    # 指定镜像
    container_name: v-redis
    image: redis:4
    command:
      # 执行的命令
      redis-server --requirepass root
  mysql:
    container_name: v-mysql
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    volumes:  
      - ./dockerRunningFile/db/mysql:/var/lib/mysql
  app:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ./settings-docker.xml:/root/.m2/settings-docker.xml
      - ./dockerRunningFile/maven/.m2/repository:/root/.m2/repository
    expose:
      - "8080"
    ports:
      # 端口映射
      - 8080:8080
    depends_on:
      - redis
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker --settings /root/.m2/settings-docker.xml 